spring:
  application:
    version: @project.version@
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

cache-provider:
  mongo:
    consumer-list:
      - consumer: bsm
        store-list:
          - store: captcha
            host: 192.168.165.34
            port: 27017
            password: asl123456
            database: captcha
            store-class-name: ricciliao.cache.pojo.dto.CaptchaCacheDto
            addition:
              timeout: 60s
              ttl: 20s
          - store: email
            host: 192.168.165.34
            port: 27017
            password: asl123456
            database: email
            store-class-name: ricciliao.cache.pojo.dto.EmailCacheDto
            addition:
              timeout: 50s
              ttl: 20s
ricciliao:
  x:
    common:
      time-zone: GMT+8