spring:
  application:
    version: @project.version@
    name: cache-provider
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

cache-provider:
  redis:
    consumer-list:
      - consumer: message
        store-list:
          - store: code
            host: 192.168.165.34
            port: 6379
            password: asl123456
            database: 1
            store-class-name: ricciliao.x.cache.pojo.message.MessageCodeCacheDto
            addition:
              max-idle: 20
              max-total: 40
              min-idle: 10
              timeout: 60s
              ttl: -1s
              statical: true
  mongo:
    consumer-list:
      - consumer: bsm
        store-list:
          - store: captcha
            host: 192.168.165.34
            port: 27017
            password: asl123456
            database: captcha
            store-class-name: ricciliao.x.cache.pojo.bsm.CaptchaCacheDto
            addition:
              ttl: 60s
          - store: email
            host: 192.168.165.34
            port: 27017
            password: asl123456
            database: email
            store-class-name: ricciliao.x.cache.pojo.bsm.EmailCacheDto
            addition:
              timeout: 60s
              statical: false
ricciliao:
  x:
    common:
      time-zone: GMT+8
    log:
      executor:
        enable: false